name: PR Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@2.0.680
        with:
          directory: tests/terraform/runner/resources/plan_rotem
          log_level: DEBUG
          quiet: false

