name: PR Test

on: pull_request

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: 'Test Plan (Checkov)'
        uses: bridgecrewio/checkov-action@master
        with:
          directory: tests/terraform/runner/resources/plan_with_child_modules
          log_level: DEBUG

